/// geodis — 3D Pedestrian Network Distance Calculator & Fieldwork Assignment Engine
///
/// Usage:
///   geodis --graph graph.bin --officers officers.csv --sites sites.csv
///          [--mode hungarian|greedy] [--output assignments.csv] [--stats]
///
/// Input CSV format:
///   officers.csv:  name,address,lon,lat[,z]
///   sites.csv:     name,address,lon,lat[,z]
///
/// The graph.bin is generated by scripts/preprocess.py from the HK 3D
/// Pedestrian Network GeoJSON data available at:
///   https://portal.csdi.gov.hk/csdi-webpage/file-api?dataset_id=landsd_rcd_1637222018065_52265&format=geojson&layer_name=PedestrianRoute

#include "graph/network_graph.hpp"
#include "routing/dijkstra.hpp"
#include "assignment/assignment_engine.hpp"

#include <iostream>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>
#include <chrono>
#include <cstdlib>
#include <iomanip>

using namespace geodis;

// ─── CSV parsing (handles quoted fields) ──────────────────────────────────────

static std::vector<std::string> split_csv_line(const std::string& line) {
    std::vector<std::string> fields;
    std::string field;
    bool in_quotes = false;

    for (size_t i = 0; i < line.size(); ++i) {
        char c = line[i];
        if (c == '"') {
            in_quotes = !in_quotes;
        } else if (c == ',' && !in_quotes) {
            fields.push_back(field);
            field.clear();
        } else {
            field += c;
        }
    }
    fields.push_back(field);
    return fields;
}

static std::vector<Location> load_csv(const std::string& path) {
    std::vector<Location> locs;
    std::ifstream in(path);
    if (!in) {
        std::cerr << "Error: Cannot open " << path << std::endl;
        std::exit(1);
    }

    std::string line;
    // Skip header
    std::getline(in, line);

    while (std::getline(in, line)) {
        if (line.empty()) continue;
        auto fields = split_csv_line(line);
        if (fields.size() < 4) continue;

        Location loc;
        loc.name = fields[0];
        loc.address = (fields.size() > 1) ? fields[1] : "";
        loc.pos.lon = std::stod(fields[2]);
        loc.pos.lat = std::stod(fields[3]);
        loc.pos.z = (fields.size() > 4 && !fields[4].empty()) ? std::stod(fields[4]) : 0.0;
        locs.push_back(loc);
    }
    return locs;
}

// ─── Output ──────────────────────────────────────────────────────────────────

static void write_csv(const std::string& path, const std::vector<Assignment>& assignments) {
    std::ofstream out(path);
    out << "officer_name,officer_address,site_name,site_address,"
        << "walking_cost,walking_distance_m,straight_line_m\n";

    for (const auto& a : assignments) {
        out << a.officer_name << ","
            << "\"" << a.officer_address << "\","
            << a.site_name << ","
            << "\"" << a.site_address << "\","
            << std::fixed << std::setprecision(1)
            << a.walking_cost << ","
            << a.walking_distance_m << ","
            << a.straight_line_m << "\n";
    }
    std::cout << "Wrote " << assignments.size() << " assignments to " << path << std::endl;
}

static void print_assignments(const std::vector<Assignment>& assignments, size_t top_n = 20) {
    std::cout << "\n═══ Top " << std::min(top_n, assignments.size()) << " Assignments ═══\n";
    std::cout << std::left
              << std::setw(20) << "Officer"
              << std::setw(20) << "Site"
              << std::setw(12) << "Walk Cost"
              << std::setw(12) << "Straight"
              << std::setw(10) << "Ratio"
              << "\n";
    std::cout << std::string(74, '-') << "\n";

    for (size_t i = 0; i < std::min(top_n, assignments.size()); ++i) {
        const auto& a = assignments[i];
        double ratio = a.straight_line_m > 0
            ? a.walking_distance_m / a.straight_line_m : 0.0;

        // Check for unreachable
        bool unreachable = (a.walking_cost >= 1e17);

        std::cout << std::left
                  << std::setw(20) << (a.officer_name.size() > 19 ? a.officer_name.substr(0, 17) + "..." : a.officer_name)
                  << std::setw(20) << (a.site_name.size() > 19 ? a.site_name.substr(0, 17) + "..." : a.site_name);
        if (unreachable) {
            std::cout << std::setw(12) << "N/A"
                      << std::setw(12) << "N/A"
                      << std::setw(10) << "N/A";
        } else {
            std::cout << std::fixed << std::setprecision(0)
                      << std::setw(12) << a.walking_cost
                      << std::setw(12) << a.straight_line_m
                      << std::setw(10) << std::setprecision(2) << ratio;
        }
        std::cout << "\n";
    }
}

// ─── GeoJSON output ──────────────────────────────────────────────────────────

static const char* edge_type_label(uint32_t flags) {
    if (flags & EDGE_STAIRS)     return "stairs";
    if (flags & EDGE_LIFT)       return "lift";
    if (flags & EDGE_ESCALATOR)  return "escalator";
    if (flags & EDGE_FOOTBRIDGE) return "footbridge";
    if (flags & EDGE_SUBWAY)     return "subway";
    if (flags & EDGE_CROSSING)   return "crossing";
    if (flags & EDGE_INDOOR)     return "indoor";
    return "footway";
}

/// Human-readable walking instruction for a single network segment.
static std::string segment_description(uint32_t flags, double len_3d,
                                       double ascent, double descent) {
    std::string verb;
    if (flags & EDGE_STAIRS)         verb = "Climb the stairs";
    else if (flags & EDGE_LIFT)      verb = "Take the lift";
    else if (flags & EDGE_ESCALATOR) verb = "Take the escalator";
    else if (flags & EDGE_FOOTBRIDGE) verb = "Cross the footbridge";
    else if (flags & EDGE_SUBWAY)    verb = "Go through the subway";
    else if (flags & EDGE_CROSSING)  verb = "Cross at the road crossing";
    else if (flags & EDGE_INDOOR)    verb = "Walk through the indoor corridor";
    else                             verb = "Walk along the footway";

    std::ostringstream os;
    os << verb << " for " << std::fixed << std::setprecision(0) << len_3d << "m";
    if (ascent > 0.5)  os << " (up " << std::setprecision(1) << ascent << "m)";
    else if (descent > 0.5) os << " (down " << std::setprecision(1) << descent << "m)";
    return os.str();
}

/// 3D euclidean distance between two points (metres).
static double point3d_distance_m(const Point3D& a, const Point3D& b) {
    double dx = (b.lon - a.lon) * 111320.0 * std::cos((a.lat + b.lat) * 0.5 * M_PI / 180.0);
    double dy = (b.lat - a.lat) * 110540.0;
    double dz = b.z - a.z;
    return std::sqrt(dx * dx + dy * dy + dz * dz);
}

static void write_geojson(const std::string& path,
                           const std::vector<Location>& officers,
                           const std::vector<Location>& sites,
                           const std::vector<Assignment>& assignments) {
    std::ofstream out(path);
    out << "{\"type\":\"FeatureCollection\",\"features\":[\n";
    bool first = true;

    auto write_comma = [&]() { if (!first) out << ",\n"; first = false; };

    // Officer markers
    for (const auto& o : officers) {
        write_comma();
        out << "{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\","
            << "\"coordinates\":[" << o.pos.lon << "," << o.pos.lat << "," << o.pos.z << "]},"
            << "\"properties\":{\"featureType\":\"officer\",\"name\":\""
            << o.name << "\",\"address\":\"" << o.address << "\"}}";
    }

    // Site markers
    for (const auto& s : sites) {
        write_comma();
        out << "{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\","
            << "\"coordinates\":[" << s.pos.lon << "," << s.pos.lat << "," << s.pos.z << "]},"
            << "\"properties\":{\"featureType\":\"site\",\"name\":\""
            << s.name << "\",\"address\":\"" << s.address << "\"}}";
    }

    // Per-segment features (for individual edge-type coloring)
    for (const auto& a : assignments) {
        if (a.path_geometry.size() < 2 || a.walking_cost >= 1e17) continue;
        if (a.path_edge_flags.empty()) continue;

        for (size_t seg = 0; seg < a.path_edge_flags.size() && seg + 1 < a.path_geometry.size(); ++seg) {
            write_comma();
            uint32_t ef = a.path_edge_flags[seg];
            const char* etype = edge_type_label(ef);

            out << "{\"type\":\"Feature\",\"geometry\":{\"type\":\"LineString\",\"coordinates\":["
                << "[" << a.path_geometry[seg].lon << "," << a.path_geometry[seg].lat << "," << a.path_geometry[seg].z << "],"
                << "[" << a.path_geometry[seg+1].lon << "," << a.path_geometry[seg+1].lat << "," << a.path_geometry[seg+1].z << "]"
                << "]},\"properties\":{"
                << "\"featureType\":\"route-segment\","
                << "\"edgeType\":\"" << etype << "\","
                << "\"officer\":\"" << a.officer_name << "\","
                << "\"site\":\"" << a.site_name << "\","
                << "\"walking_cost\":" << a.walking_cost << ","
                << "\"straight_line\":" << a.straight_line_m << ","
                << "\"ascent\":" << a.path_ascent << ","
                << "\"descent\":" << a.path_descent << ","
                << "\"segment_index\":" << seg << ","
                << "\"is_covered\":" << ((ef & EDGE_COVERED) ? "true" : "false") << ","
                << "\"is_steep\":" << ((ef & EDGE_STEEP) ? "true" : "false") << ","
                << "\"has_barrier\":" << ((ef & EDGE_BARRIER) ? "true" : "false")
                << "}}";
        }
    }

    // Full continuous route features (one per officer→site, all waypoints merged)
    for (const auto& a : assignments) {
        if (a.path_geometry.size() < 2 || a.walking_cost >= 1e17) continue;

        write_comma();
        out << "{\"type\":\"Feature\",\"geometry\":{\"type\":\"LineString\",\"coordinates\":[";
        for (size_t j = 0; j < a.path_geometry.size(); ++j) {
            if (j > 0) out << ",";
            out << "[" << a.path_geometry[j].lon << "," << a.path_geometry[j].lat << "," << a.path_geometry[j].z << "]";
        }
        out << "]},\"properties\":{"
            << "\"featureType\":\"full-route\","
            << "\"officer\":\"" << a.officer_name << "\","
            << "\"site\":\"" << a.site_name << "\","
            << "\"walking_cost\":" << a.walking_cost << ","
            << "\"straight_line\":" << a.straight_line_m << ","
            << "\"ascent\":" << a.path_ascent << ","
            << "\"descent\":" << a.path_descent << ","
            << "\"waypoint_count\":" << a.path_geometry.size() << ","
            << "\"officer_address\":\"" << a.officer_address << "\","
            << "\"site_address\":\"" << a.site_address << "\","
            << "\"narrative\":[";

        // Build a readable turn-by-turn walking narrative: merge consecutive
        // segments that share the same travel mode (footway, stairs, lift,
        // escalator, footbridge, subway, crossing, indoor).
        {
            constexpr uint32_t MODE_MASK =
                EDGE_STAIRS | EDGE_LIFT | EDGE_ESCALATOR | EDGE_FOOTBRIDGE |
                EDGE_SUBWAY | EDGE_CROSSING | EDGE_INDOOR;

            size_t j = 0;
            bool first_step = true;
            while (j + 1 < a.path_geometry.size()) {
                uint32_t ef = (j < a.path_edge_flags.size()) ? a.path_edge_flags[j] : 0;
                uint32_t mode = ef & MODE_MASK;

                double total_len = 0.0, total_asc = 0.0, total_desc = 0.0;
                size_t k = j;
                while (k + 1 < a.path_geometry.size()) {
                    uint32_t ef2 = (k < a.path_edge_flags.size()) ? a.path_edge_flags[k] : 0;
                    if ((ef2 & MODE_MASK) != mode) break;
                    total_len += point3d_distance_m(a.path_geometry[k], a.path_geometry[k + 1]);
                    double dz = a.path_geometry[k + 1].z - a.path_geometry[k].z;
                    if (dz > 0) total_asc += dz; else total_desc += -dz;
                    ++k;
                }

                std::string s = segment_description(ef, total_len, total_asc, total_desc);
                std::string escaped;
                for (char c : s) {
                    if (c == '"') escaped += "\\\"";
                    else if (c == '\\') escaped += "\\\\";
                    else escaped += c;
                }
                if (!first_step) out << ",";
                first_step = false;
                out << "\"" << escaped << "\"";

                j = k;
            }
        }
        out << "]"
            << "}}";
    }

    out << "\n]}\n";
    std::cout << "Wrote routes GeoJSON to " << path << std::endl;
}

// ─── Main ────────────────────────────────────────────────────────────────────

int main(int argc, char* argv[]) {
    std::string graph_path = "graph.bin";
    std::string officers_path;
    std::string sites_path;
    std::string output_path;
    std::string geojson_path;
    std::string mode_str = "hungarian";
    double cluster_penalty = 0.15;
    bool show_stats = false;
    bool compute_geometry = false;

    // Simple arg parsing
    for (int i = 1; i < argc; ++i) {
        std::string arg = argv[i];
        if (arg == "--graph" && i + 1 < argc) graph_path = argv[++i];
        else if (arg == "--officers" && i + 1 < argc) officers_path = argv[++i];
        else if (arg == "--sites" && i + 1 < argc) sites_path = argv[++i];
        else if (arg == "--output" && i + 1 < argc) output_path = argv[++i];
        else if (arg == "--geojson" && i + 1 < argc) { geojson_path = argv[++i]; compute_geometry = true; }
        else if (arg == "--geometry") compute_geometry = true;
        else if (arg == "--mode" && i + 1 < argc) mode_str = argv[++i];
        else if (arg == "--cluster-penalty" && i + 1 < argc) cluster_penalty = std::stod(argv[++i]);
        else if (arg == "--stats") show_stats = true;
        else if (arg == "--help" || arg == "-h") {
            std::cout << R"(geodis — 3D Pedestrian Network Fieldwork Assignment Engine

Usage: geodis [options]

Options:
  --graph FILE     Binary graph file (default: graph.bin)
  --officers FILE  CSV file with officer names/addresses/coordinates
  --sites FILE     CSV file with fieldwork site names/addresses/coordinates
  --output FILE    Output CSV for assignments (default: stdout summary only)
  --geojson FILE   Output walking routes as GeoJSON (implies --geometry)
  --geometry       Compute path geometry for assignments
  --mode MODE      Assignment mode: hungarian (optimal) | greedy | cluster
  --cluster-penalty P  Load-balancing penalty for cluster mode (default 0.15)
  --stats          Print network statistics and exit
  --help, -h       Show this help

CSV format (header required):
  name,address,lon,lat[,z]

Binary graph format:
  Generated by scripts/preprocess.py from HK 3D Pedestrian Network GeoJSON.
  Download data from CSDI Portal:
    https://portal.csdi.gov.hk/csdi-webpage/file-api?dataset_id=landsd_rcd_1637222018065_52265&format=geojson&layer_name=PedestrianRoute
)";
            return 0;
        }
    }

    // ── Load graph ────────────────────────────────────────────────────────
    std::cout << "Loading graph from " << graph_path << "..." << std::endl;
    auto t0 = std::chrono::steady_clock::now();

    NetworkGraph graph = NetworkGraph::load(graph_path);

    auto t1 = std::chrono::steady_clock::now();
    auto load_ms = std::chrono::duration_cast<std::chrono::milliseconds>(t1 - t0).count();

    std::cout << "Loaded " << graph.node_count() << " nodes, "
              << graph.edge_count() << " edges in "
              << load_ms << " ms" << std::endl;

    if (show_stats) {
        auto s = graph.stats();
        std::cout << "\n═══ Network Statistics ═══\n";
        std::cout << "Total 2D length: " << std::fixed << std::setprecision(1) << s.total_2d_km << " km\n";
        std::cout << "Total 3D length: " << s.total_3d_km << " km\n";
        std::cout << "Stairs: " << s.num_stairs
                  << "  Lifts: " << s.num_lifts
                  << "  Footbridges: " << s.num_footbridges
                  << "  Subways: " << s.num_subways << "\n";
        std::cout << "Indoor: " << s.num_indoor
                  << "  Barrier-free: " << s.num_barrier_free << "\n";
        std::cout << "Elevation range: " << s.min_z << "m to " << s.max_z << "m\n";
    }

    if (officers_path.empty() || sites_path.empty()) {
        if (!show_stats)
            std::cerr << "Error: --officers and --sites required (use --help)\n";
        return show_stats ? 0 : 1;
    }

    // ── Load locations ────────────────────────────────────────────────────
    auto officers = load_csv(officers_path);
    auto sites = load_csv(sites_path);
    std::cout << "Officers: " << officers.size()
              << "  Sites: " << sites.size() << std::endl;

    // ── Assign ────────────────────────────────────────────────────────────
    auto mode = (mode_str == "greedy")
        ? AssignmentEngine::Mode::GREEDY
        : (mode_str == "cluster")
        ? AssignmentEngine::Mode::CLUSTER
        : AssignmentEngine::Mode::HUNGARIAN;

    AssignmentEngine engine(graph, mode);
    engine.set_compute_geometry(compute_geometry);
    engine.set_cluster_load_penalty(cluster_penalty);
    auto assignments = engine.assign(officers, sites);

    auto t2 = std::chrono::steady_clock::now();
    auto assign_ms = std::chrono::duration_cast<std::chrono::milliseconds>(t2 - t1).count();

    print_assignments(assignments);

    std::cout << "\nTotal time: load=" << load_ms << "ms  assign=" << assign_ms << "ms";

    if (compute_geometry) {
        std::cout << " (with path geometry)";
    }
    std::cout << "\n";

    if (!output_path.empty()) {
        write_csv(output_path, assignments);
    }

    if (!geojson_path.empty()) {
        write_geojson(geojson_path, officers, sites, assignments);
    }

    return 0;
}
